spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: 1314
    url: jdbc:mysql://localhost:3306/blog?serverTimezone=UTC&useUnicode=true&characterEndoing=UTF-8
    type: com.alibaba.druid.pool.DruidDataSource

  jpa:
   hibernate:
     ddl-auto: none
    show-sql: true

#    日志
logging:
  level:
    root: warn
    com.atjiandong.blog: info
  file:
      path: log/blog-pro.log
server:
  port: 8081